"""
Config file creation/validation and provider setup for Rout.
"""

import json
import os
import platform
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from .ui import ok, warn, fail, ask, ask_choice, BOLD, DIM, NC
from .checks import get_system_ram_gb, is_apple_silicon
from .launchd import setup_ollama_autostart


# ── Config Loading ────────────────────────────────────────────────────────────

def load_existing_config():
    """Load existing config for defaults, if any."""
    config_file = Path.home() / ".openclaw" / "config.yaml"
    if not config_file.exists():
        return {}
    try:
        import yaml
        with open(config_file) as f:
            return yaml.safe_load(f) or {}
    except Exception:
        return {}


def write_config(config, config_file, is_local, cloud_model, model_name):
    """
    Write config to file with backup.

    Args:
        config: Config dict to write
        config_file: Path to config file
        is_local: Whether in local mode
        cloud_model: Cloud model name (if cloud mode)
        model_name: Local model name (if local mode)
    """
    import yaml

    if config_file.exists():
        backup = config_file.with_suffix(".yaml.bak")
        shutil.copy2(config_file, backup)
        ok(f"Backed up existing config to {backup.name}")

    mode_label = "LOCAL-ONLY MODE (Qwen via Ollama)" if is_local else "CLOUD MODE (Anthropic Claude)"
    with open(config_file, "w") as f:
        f.write(f"# Rout config — {mode_label}\n")
        f.write("# Generated by: python3 setup.py\n")
        f.write("# Edit freely. Re-run to reconfigure.\n\n")
        yaml.dump(config, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    os.chmod(config_file, 0o600)
    ok(f"Config saved to {config_file}")


# ── API Key Testing ───────────────────────────────────────────────────────────

def test_api_key(key):
    """
    Send a minimal request to verify the API key works.

    Returns:
        (success, error_msg) — (bool, str or None)
    """
    try:
        import requests
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": key,
                "content-type": "application/json",
                "anthropic-version": "2023-06-01",
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 10,
                "messages": [{"role": "user", "content": "Say ok"}],
            },
            timeout=15,
        )
        if resp.status_code == 200:
            return True, None
        elif resp.status_code == 401:
            return False, "Invalid key (401 Unauthorized)"
        elif resp.status_code == 403:
            return False, "Key doesn't have API access (403 Forbidden)"
        else:
            return False, f"API returned {resp.status_code}: {resp.text[:100]}"
    except Exception as e:
        return False, f"Connection error: {e}"


# ── Cloud Provider Setup ──────────────────────────────────────────────────────

def get_cloud_provider_options():
    """Return available cloud provider options."""
    return [
        (
            "Anthropic Claude (Sonnet 4.5) — best quality, API key required",
            {"provider": "anthropic", "model": "claude-sonnet-4-5"},
        ),
        (
            "Anthropic Claude (Haiku 4.5) — faster + cheaper, lower quality",
            {"provider": "anthropic", "model": "claude-haiku-4-5-20251001"},
        ),
    ]


def setup_cloud_provider(existing):
    """
    Configure cloud provider.

    Returns:
        (api_key, cloud_model, cloud_config) — (str, str, dict)
    """
    from .keys import validate_api_key

    print(f"\n{BOLD}Cloud Provider{NC}")
    print("-" * 30)

    # Choose provider/model
    provider_options = get_cloud_provider_options()
    cloud_choice = ask_choice(
        "Which cloud model?",
        provider_options,
        default=1,
    )

    cloud_model = cloud_choice["model"]
    ok(f"Selected: {cloud_model}")

    # API key
    print(f"\n{BOLD}Anthropic API key{NC}")
    print("-" * 30)
    print(f"  {DIM}Get one at: https://console.anthropic.com/settings/keys{NC}")

    existing_key = ""
    for k in ["anthropic_api_key"]:
        if existing.get(k, "") and "XXXX" not in str(existing[k]):
            existing_key = existing[k]
            break
    for section in ["claude", "anthropic"]:
        nested = existing.get(section, {})
        if isinstance(nested, dict):
            for k in ["api_key"]:
                v = nested.get(k, "")
                if v and "XXXX" not in str(v):
                    existing_key = v
                    break

    if existing_key:
        masked = f"{existing_key[:8]}...{existing_key[-4:]}"
        print(f"  {DIM}Current key: {masked}{NC}")
        keep = ask("Keep existing key? (Y/n)", default="y")
        if keep.lower().startswith("y"):
            api_key = existing_key
        else:
            api_key = ask("Paste your API key", validate=validate_api_key, required=True)
    else:
        api_key = ask("Paste your API key", validate=validate_api_key, required=True)

    # Test
    print("  Testing API key...")
    success, err = test_api_key(api_key)
    if success:
        ok("API key is valid")
    else:
        warn(f"Key test failed: {err}")
        proceed = ask("Save anyway? (y/N)", default="n")
        if not proceed.lower().startswith("y"):
            print("Setup cancelled. Re-run when you have a valid key.")
            sys.exit(1)

    cloud_config = {
        "model": cloud_model,
        "max_tokens": 4096,
    }

    return api_key, cloud_model, cloud_config


# ── Local Provider Setup ──────────────────────────────────────────────────────

def get_local_model_options(ram_gb):
    """Return available model options based on system RAM."""
    options = []

    # Always show options that fit in RAM
    if ram_gb >= 8:
        options.append((
            f"Qwen 3.5 7B — fast, basic quality (~5GB VRAM)",
            {"model": "qwen3.5:7b", "gpu_mem_mb": 8192, "ctx": 32768},
        ))

    if ram_gb >= 16:
        options.append((
            f"Qwen 3.5 14B — good balance of speed and quality (~10GB VRAM)",
            {"model": "qwen3.5:14b", "gpu_mem_mb": 12288, "ctx": 32768},
        ))

    if ram_gb >= 32:
        options.append((
            f"Qwen 3.5 27B — recommended, full tool calling (~18GB VRAM)",
            {"model": "qwen3.5:27b", "gpu_mem_mb": 24576, "ctx": 32768},
        ))

    if ram_gb >= 48:
        options.append((
            f"Qwen 3.5 35B-A3B — MoE, best at this size (~24GB VRAM)",
            {"model": "qwen3.5:35b-a3b", "gpu_mem_mb": 32768, "ctx": 32768},
        ))

    if ram_gb >= 64:
        options.append((
            f"Qwen 3.5 32B — dense, highest quality sub-70B (~22GB VRAM)",
            {"model": "qwen3.5:32b", "gpu_mem_mb": 32768, "ctx": 32768},
        ))

    return options


def install_ollama():
    """Install Ollama if not present."""
    if shutil.which("ollama"):
        return True

    print(f"\n  Installing Ollama...")
    brew_path = shutil.which("brew")
    if brew_path:
        result = subprocess.run(
            [brew_path, "install", "ollama"],
            capture_output=False, timeout=300,
        )
        if result.returncode == 0 and shutil.which("ollama"):
            ok("Ollama installed via Homebrew")
            return True

    # Fallback to curl installer
    try:
        result = subprocess.run(
            ["bash", "-c", "curl -fsSL https://ollama.com/install.sh | sh"],
            capture_output=True, text=True, timeout=300,
        )
        if shutil.which("ollama"):
            ok("Ollama installed")
            return True
    except Exception:
        pass

    fail("Could not install Ollama. Install manually: https://ollama.com/download")
    return False


def ensure_ollama_running():
    """Start Ollama server if not already running."""
    try:
        req = urllib.request.Request("http://localhost:11434/api/tags")
        urllib.request.urlopen(req, timeout=3)
        return True
    except Exception:
        pass

    print(f"  Starting Ollama server...")
    subprocess.Popen(
        ["ollama", "serve"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    # Wait for it to come up
    for _ in range(10):
        time.sleep(1)
        try:
            req = urllib.request.Request("http://localhost:11434/api/tags")
            urllib.request.urlopen(req, timeout=3)
            ok("Ollama server started")
            return True
        except Exception:
            continue

    fail("Ollama server did not start. Run manually: ollama serve")
    return False


def pull_model(model_name):
    """Pull an Ollama model. Shows progress."""
    print(f"\n  Pulling {model_name} — this may take 10-30 minutes on first run...")
    print(f"  {DIM}(Progress shown below){NC}\n")

    result = subprocess.run(
        ["ollama", "pull", model_name],
        capture_output=False,
        timeout=1800,  # 30 min timeout
    )

    if result.returncode == 0:
        ok(f"Model {model_name} ready")
        return True
    else:
        fail(f"Failed to pull {model_name}. Run manually: ollama pull {model_name}")
        return False


def test_local_inference(model_name):
    """Quick inference test to verify the model works."""
    print(f"  Testing inference...")
    try:
        body = json.dumps({
            "model": model_name,
            "messages": [{"role": "user", "content": "Say 'online' in one word."}],
            "stream": False,
            "options": {"num_predict": 10},
        }).encode("utf-8")
        req = urllib.request.Request(
            "http://localhost:11434/api/chat",
            data=body,
            headers={"Content-Type": "application/json"},
        )
        resp = urllib.request.urlopen(req, timeout=120)
        result = json.loads(resp.read())
        text = result.get("message", {}).get("content", "").strip()
        if text:
            ok(f"Inference test passed: \"{text}\"")
            return True
        else:
            warn("Model returned empty response — may still work in practice")
            return True
    except Exception as e:
        fail(f"Inference test failed: {e}")
        return False


def test_local_tool_calling(model_name):
    """Test that the model can handle function calling."""
    print(f"  Testing tool calling...")
    try:
        body = json.dumps({
            "model": model_name,
            "messages": [{"role": "user", "content": "What's the weather today? Use the search tool."}],
            "tools": [{
                "type": "function",
                "function": {
                    "name": "web_search",
                    "description": "Search the web for current information.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "query": {"type": "string", "description": "Search query"},
                        },
                        "required": ["query"],
                    },
                },
            }],
            "stream": False,
            "options": {"num_predict": 100},
        }).encode("utf-8")
        req = urllib.request.Request(
            "http://localhost:11434/api/chat",
            data=body,
            headers={"Content-Type": "application/json"},
        )
        resp = urllib.request.urlopen(req, timeout=120)
        result = json.loads(resp.read())
        tool_calls = result.get("message", {}).get("tool_calls", [])
        if tool_calls:
            name = tool_calls[0].get("function", {}).get("name", "?")
            ok(f"Tool calling works — model called {name}()")
            return True
        else:
            warn("Model didn't use tool calling on test prompt — may work with real prompts")
            return True
    except Exception as e:
        warn(f"Tool calling test inconclusive: {e}")
        return True  # Non-fatal


def setup_local_provider(existing):
    """
    Configure local provider.

    Returns:
        (model_name, local_config) — (str, dict)
    """
    print(f"\n{BOLD}Local Model{NC}")
    print("-" * 30)

    ram_gb = get_system_ram_gb()
    model_options = get_local_model_options(ram_gb)

    if not model_options:
        fail(f"No models available for {ram_gb}GB RAM. Minimum 8GB required.")
        sys.exit(1)

    # Default to the largest model that fits
    default_idx = len(model_options)

    model_choice = ask_choice(
        f"Choose your model ({ram_gb}GB RAM detected):",
        model_options,
        default=default_idx,
    )

    model_name = model_choice["model"]
    gpu_mem_mb = model_choice["gpu_mem_mb"]
    ctx_length = model_choice["ctx"]

    ok(f"Selected: {model_name}")

    # Install Ollama if needed
    if not install_ollama():
        sys.exit(1)

    # Start Ollama
    if not ensure_ollama_running():
        sys.exit(1)

    # Set GPU memory cap
    if platform.system() == "Darwin":
        print(f"  Setting GPU memory cap to {gpu_mem_mb}MB...")
        try:
            subprocess.run(
                ["sudo", "sysctl", f"iogpu.wired_limit_mb={gpu_mem_mb}"],
                capture_output=True, timeout=10,
            )
            ok(f"GPU memory cap set to {gpu_mem_mb}MB")
        except Exception:
            warn("Could not set GPU memory cap (may need sudo). Continuing...")

    # Pull model
    if not pull_model(model_name):
        proceed = ask("Model pull failed. Continue anyway? (y/N)", default="n")
        if not proceed.lower().startswith("y"):
            sys.exit(1)

    # Test inference
    test_local_inference(model_name)
    test_local_tool_calling(model_name)

    # Auto-start
    if platform.system() == "Darwin":
        setup_ollama_autostart()

    local_config = {
        "enabled": True,
        "provider": "ollama",
        "host": "http://localhost:11434",
        "model": model_name,
        "timeout_seconds": 120,
        "max_tokens": 4096,
        "temperature": 0.7,
        "context_length": ctx_length,
        "gpu_memory_cap_mb": gpu_mem_mb,
    }

    return model_name, local_config
